### ISSUE TITLE
GetNames is not a function when I tried to rebuild

### ISSUE THREAD

**Issue by thibmonier** [lando/core#346]
Im'using 3.24 (updated today).
When I'm rebuilding my stack this message each times : ERROR ==> utils.getNamedVolumes is not a function

Any ideas ?

**Comment by pirog** [comment]
@thibmonier i see where this went astray. let me roll a patch release quickly for you.

**Comment by thibmonier** [comment]
unfortunately I'm still having this error after updating to 3.24.1
`  lando ERROR TypeError: utils.getNamedVolumes is not a function
    at new LandoMounter (/Users/tmonier/.lando/plugins/@lando/core/builders/_mounter.js:32:24)
    at AsyncEvents.<anonymous> (/Users/tmonier/.lando/plugins/@lando/core/hooks/app-load-legacy-sharing.js:65:27)
    at AsyncEvents.handle (/Users/tmonier/.lando/plugins/@lando/core/lib/events.js:88:25)
    at /Users/tmonier/.lando/plugins/@lando/core/lib/events.js:124:21
From previous event:
    at AsyncEvents.emit (/Users/tmonier/.lando/plugins/@lando/core/lib/events.js:113:20)
    at /Users/tmonier/.lando/plugins/@lando/core/lib/app.js:510:29
From previous event:
    at App.start (/Users/tmonier/.lando/plugins/@lando/core/lib/app.js:510:6)
    at /Users/tmonier/.lando/plugins/@lando/core/lib/app.js:456:22
    at async Object.run (/Users/tmonier/.lando/plugins/@lando/core/tasks/restart.js:25:11)  +24ms
  lando reporting error action to url=https://metrics.lando.dev, report=true +21ms
  lando reporting data command=lando restart, context=local, devMode=false, instance=eb1c4fcf16f33ad8f7b9699497517f17e57ee5b4, nodeVersion=v20.18.0, mode=cli, type=Darwin, platform=darwin, landoPlatform=darwin, release=24.4.0, arch=arm64, isWsl=false, isWslInterop=false, product=lando, version=3.24.0, message=utils.getNamedVolumes is not a function, stack=TypeError: utils.getNamedVolumes is not a function
    at new LandoMounter (_mounter.js:32:24)
    at AsyncEvents.<anonymous> (app-load-legacy-sharing.js:65:27)
    at AsyncEvents.handle (events.js:88:25)
    at /Users/tmonier/.lando/plugins/@lando/core/lib/events.js:124:21
From previous event:
    at AsyncEvents.emit (events.js:113:20)
    at /Users/tmonier/.lando/plugins/@lando/core/lib/app.js:510:29
From previous event:
    at App.start (app.js:510:6)
    at /Users/tmonier/.lando/plugins/@lando/core/lib/app.js:456:22
    at async Object.run (restart.js:25:11), action=error, created=2025-03-04T06:11:53.274Z +1ms`

**Comment by pirog** [comment]
@thibmonier run `lando version --all` to verify you are on the correct version. Based on the paths i see in the debug output it doesnt look like its using the new version. It might be beneficial to just remove that legacy core version with `rm -rf /Users/tmonier/.lando/plugins/@lando/core`

**Comment by thibmonier** [comment]
I have to finally reinstall lando with the last version to be able to rebuild it.
